fesbuk2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import login.urls as login
import user_forum.urls as user_forum
import browse.urls as browse
import profiles.urls as profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include(browse, namespace="browse")),
    url(r'^profile/', include(profile, namespace="profile")),
    url(r'^login/', include(login, namespace="login")),
    url(r'^forum/', include(user_forum, namespace="forum")),
]

login/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth_login/$', auth_login, name='auth_login'),
    url(r'^custom_auth_logout/$', auth_logout, name='auth_logout'),
    url(r'^create_company/$', create_company, name='create_company'),
    url(r'^dashboard/$', dashboard, name='dashboard'),

]

user_forum/urls.py
from django.conf.urls import url
from .views import index, add_lowongan

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'add-lowongan', add_lowongan, name="add-lowongan"),
]

user_forum/models.py
from django.db import models

# Create your models here.
class Forum(models.Model):
    kode_identitas = models.CharField('Kode Identitas', max_length=50, primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Lowongan(models.Model):
    forum = models.ForeignKey(Forum)
    lowongan = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

user_forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Forum, Lowongan

# Create your views here.
response = {}
'''with login
def index(request):
    if 'ver_id' not in request.session.keys():
        return HttpResponseRedirect(reverse('login:index'))
    else:
        kode_identitas = request.session['ver_id']
        try:
            forum = Forum.objects.get(kode_identitas=kode_identitas)
        except Exception:
            forum = Forum()
            forum.kode_identitas = kode_identitas
            forum.save()
        lowongan = Lowongan.objects.filter(forum=forum)
        paginator = Paginator(lowongan, 1)
        page = request.GET.get('page')
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        response['lowongan'] = data
        html = 'user_forum/user_forum.html'
        return render(request, html, response)
    '''
'''without login'''
def index(request):
        kode_identitas = 1
        try:
            forum = Forum.objects.get(kode_identitas=kode_identitas)
        except Exception:
            forum = Forum()
            forum.kode_identitas = kode_identitas
            forum.save()
        lowongan = Lowongan.objects.filter(forum=forum)
        paginator = Paginator(lowongan, 1)
        page = request.GET.get('page')
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        response['lowongan'] = data
        html = 'user_forum/user_forum.html'
        return render(request, html, response)

'''with login
@csrf_exempt
def add_lowongan(request):
    if(request.method == "POST"):
        kode_identitas = request.session['ver_id']
        forum = Forum.objects.get(kode_identitas=kode_identitas)
        lowongan = lowongan(forum)
        lowongan.lowongan(request.POST['input'])
        lowongan.save()
        data = {'input' : request.POST['input']}
        return JsonResponse(data)
    else:
        return HttpResponseRedirect('/forum/')
    '''

'''without login'''
@csrf_exempt
def add_lowongan(request):
    if(request.method == "POST"):
        data = request.POST['input']
        kode_identitas = 1
        forum = Forum.objects.get(kode_identitas=kode_identitas)
        lowongan = Lowongan(forum=forum, lowongan=data).save()
        response = {'input' : data}
        return JsonResponse(response)
    else:
        return HttpResponseRedirect('/forum/')

user_forum/templates/user_forum/user_forum.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
Forum Lowongan
{% endblock %}

{% block styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/user_forum.css' %}"/>
{% endblock %}

{% block content %}
  <h1 class="judul">Forum</h1>
  <div class="forum_lowongan">
  {% for data in lowongan %}
    <div class="item margin10px">
      <h4>{{ data.lowongan }}</h4>
    </div>
  {% endfor %}
  </div>
  <div class="pagination margin10px">
    <span class="step-links">
      {% if lowongan.has_previous %}
      <a href="?page={{ lowongan.previous_page_number }}">previous</a>
      {% endif %}
      <span class="current">
        Page {{ lowongan.number }} of {{ lowongan.paginator.num_pages }}.
      </span>
      {% if lowongan.has_next %}
        <a href="?page={{ lowongan.next_page_number }}">next</a>
      {% endif %}
    </span>
  </div>
  <br>
  <center>
    <button onclick="tambah_forum()">Tambah Forum Lowongan</button>
  </center>

{% endblock %}

{% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script>
    function tambah_forum() {
      var html = '<div id="tambah-forum">' +
      '<textarea id="field_forum" cols="50" rows="4" type="text" placeholder="Masukkan deskripsi..." class="status-form-textarea margin10px" maxlength="150" required ></textarea>' +
      '<br>' +
      '<button class="margin10px" onclick="tambah_lowongan()">Submit</button>' +
      '</div>';
      $(".forum_lowongan").append(html);
    };

    function tambah_lowongan() {
      var input = $('#field_forum').val();
      $.ajax({
        method: "POST",
        url: '{% url "forum:add-lowongan" %}',
        data: {'input' : input},
        dataType: 'json',
        success : function(response) {
          $('#tambah-forum').remove();
          alert("Berhasil Ditambahkan");
        },
        error : function(error) {
          alert("error")
        }
      });
    };
  </script>
{% endblock %}