fesbuk2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import login.urls as login
import user_forum.urls as user_forum
import browse.urls as browse
import profiles.urls as profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include(browse, namespace="browse")),
    url(r'^profile/', include(profile, namespace="profile")),
    url(r'^login/', include(login, namespace="login")),
    url(r'^forum/', include(user_forum, namespace="forum")),
]

login/urls.py
from django.conf.urls import url
from .views import *
from .custom_auth import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),

    # custom auth
    url(r'^custom_auth_login/$', auth_login, name='auth_login'),
    url(r'^custom_auth_logout/$', auth_logout, name='auth_logout'),
    url(r'^create_company/$', create_company, name='create_company'),
    url(r'^dashboard/$', dashboard, name='dashboard'),

]

templates/partials/header.html
<nav class="navbar navbar-inverse navbar-fesbuktwo">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'browse:index' %}">FESBUKTWO</a>
        </div>
        
        <ul class="nav navbar-nav navbar-right">
            {% if is_authorized %}
                <li id="navbar-nav-company"><a href="{% url 'profile:index' %}">BukaHati</a></li>
                <li><a href="{% url 'login:auth_logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            {% else %}
                <li><a href="{% url 'login:auth_login' %}"><span class="glyphicon glyphicon-log-in"></span>&nbsp Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div id="navbar-space"></div>